### ISSUE TITLE
Status code e range de respostas

### ISSUE THREAD

**Issue by FelipeGOMeli** [anagiorgiani/onbording-it#3]
Ao avaliar possíveis respostas válidas, é mais interessante ter o status codes esperados bem definidos do que um range. Isso evita respostas inesperadas e que não estamos prontos para tratar, além de deixar a manutenção mais fácil no futuro, já que quem for atuar tem bem claro quais são as possibilidades.

Além disso, é possível também utlizar a lib **http** nativa do Golang para usar as constantes de status code, facilita bastante.

https://github.com/anagiorgiani/onbording-it/blob/1df116eca87a6acda776ed8cae8c70c86320b1c3/pkg/web/response.go#L10

**Comment by anagiorgiani** [comment]
feito <3
