### ISSUE TITLE
Organização de pacotes e arquitetura hexagonal

### ISSUE THREAD

**Issue by FelipeGOMeli** [anagiorgiani/onbording-it#4]
A gente pode organizar alguns pacotes de um jeito um pouco mais parecido com o que usamos hoje na home que usa a arquitetura hexagonal. Relaxa que é bem confuso pra gente que veio de outra linguagem, mas rapidinho vc acostuma. 

Lá no [best practices](https://docs.google.com/presentation/d/18Ipw16GrkKXdVb-ujSa1FQSjwvnC7ealOBZkrYhO8zY/edit#slide=id.g12042151dcb_0_0) tem um exemplo, mas se precisar posso explicar com mais detalhes.

**Comment by anagiorgiani** [comment]
feito <3 , não  sei se 100% mas conforme meu entendimento realizei as modificações
