### ISSUE TITLE
Tratamento de erros

### ISSUE THREAD

**Issue by FelipeGOMeli** [anagiorgiani/onbording-it#7]
Mesmo sendo bem difícil que essas funções falhem, é sempre uma boa prática tentar tratá-los para que caso aconteçam a gente consiga seguir com a API rodando e devolver uma resposta mesmo que com partial. Vale colocar um 
`if err != nil` nesses casos

https://github.com/anagiorgiani/onbording-it/blob/1df116eca87a6acda776ed8cae8c70c86320b1c3/internal/my_api/service/service.go#L45

https://github.com/anagiorgiani/onbording-it/blob/1df116eca87a6acda776ed8cae8c70c86320b1c3/internal/my_api/service/service.go#L46

**Comment by anagiorgiani** [comment]
feito <3
